SysLab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from django.conf import settings
from django.conf.urls.static import static
from .core import views
from django.contrib.auth import views as auth_views

from rest_framework.urlpatterns import format_suffix_patterns

router = DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'group', views.GroupViewSet)
router.register(r'classroom', views.ClassroomViewSet)
router.register(r'request', views.RequestViewSet)
router.register(r'so', views.SOViewSet)
router.register(r'pc', views.PCViewSet)
router.register(r'pc_so_sw', views.PC_SO_SWViewSet)
router.register(r'sw', views.SWViewSet)
# The API URLs are now determined automatically by the router.

urlpatterns = [

    # admin y api
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # login
    url(r'^index/', views.index , name='index'),

    # index, login y logout
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # se puede hacer una logout view pero por ahora redirije a login nomas, en settings esta configurado
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    # Aulas
    url(r'^aulas/(?P<pk>[0-9]+)/$', views.classroom_detail, name='aulaDetail'),
    url(r'^aulas/(?P<pk>[0-9]+)/borrar/$', views.classroom_delete, name='aulaDelete'),
    url(r'^aulas/(?P<pk>[0-9]+)/editar/$', views.classroom_edit, name='aulaEdit'),
    url(r'^aulas/crear/', views.classroom_create, name='aulaCreate'),
    url(r'^aulas/', views.classrooms, name='aulas'),

    # Establecimientos
    url(r'^establecimientos/(?P<pk>[0-9]+)/$', views.establishment_detail, name='establecimientoDetail'),
    url(r'^establecimientos/(?P<pk>[0-9]+)/borrar/$', views.establishment_delete, name='establecimientoDelete'),
    url(r'^establecimientos/(?P<pk>[0-9]+)/editar/$', views.establishment_edit, name='establecimientoEdit'),
    url(r'^establecimientos/crear/', views.establishment_create, name='establecimientoCreate'),
    url(r'^establecimientos/', views.establishments, name='establecimientos'),

    # SOs
    url(r'^sos/(?P<pk>[0-9]+)/$', views.so_detail, name='soDetail'),
    url(r'^sos/(?P<pk>[0-9]+)/borrar/$', views.so_delete, name='soDelete'),
    url(r'^sos/(?P<pk>[0-9]+)/editar/$', views.so_edit, name='soEdit'),
    url(r'^sos/crear/', views.so_create, name='soCreate'),
    url(r'^sos/', views.sos, name='sos'),
    url(r'^ajax/so/', views.so_by_pc, name='ajax_so_by_pc'),

    # PCs
    url(r'^pcs/(?P<pk>[0-9]+)/$', views.pc_detail, name='pcDetail'),
    url(r'^pcs/(?P<pk>[0-9]+)/borrar/$', views.pc_delete, name='pcDelete'),
    url(r'^pcs/(?P<pk>[0-9]+)/editar/$', views.pc_edit, name='pcEdit'),
    url(r'^pcs/crear/', views.pc_create, name='pcCreate'),
    url(r'^pcs/(?P<pk>[0-9]+)/clonar/$', views.pc_clone, name='pcClone'),
    url(r'^pcs/$', views.pcs, name='pcs'),

    # SW
    url(r'^sws/(?P<pk>[0-9]+)/$', views.sw_detail, name='swDetail'),
    url(r'^sws/(?P<pk>[0-9]+)/borrar/$', views.sw_delete, name='swDelete'),
    url(r'^sws/(?P<pk>[0-9]+)/editar/$', views.sw_edit, name='swEdit'),
    url(r'^sws/crear/', views.sw_create, name='swCreate'),
    url(r'^sws/asignar/pc/', views.sw_assign, name='swAssign'),
    url(r'^sws/asignaciones/(?P<pk>[0-9]+)/borrar/$', views.sw_assignment_delete, name='swAssignmentDelete'),
    url(r'^sws/asignaciones/', views.sw_assignments, name='swAssignments'),
    url(r'^sws/asignar/aula/', views.sw_so_classroom_assignment, name='swSOClassroomAssignment'),
    url(r'^sws/', views.sws, name='sws'),

    # Reserva
    url(r'^reservas/$', views.reservations, name='reservations'),
    url(r'^reservas/listado/$', views.reservations_listado, name='reservations_listado'),
    url(r'^reservas/(?P<pk>[0-9]+)/editar/$', views.reservation_edit, name='reservationEdit'),
    url(r'^reservas/(?P<pk>[0-9]+)/$', views.reservation_detail, name='reservationDetail'),
    url(r'^reservas/(?P<pk>[0-9]+)/borrar/$', views.reservation_delete, name='reservationDelete'),

    # Slots
    url(r'^ranuras/crear/reserva/(?P<pk_reserva>[0-9]+)/$', views.slots_reservation_create, name='slotsReservationCreate'),
    url(r'^ranuras/crear/solicitud/(?P<pk_solicitud>[0-9]+)/$',views.slots_request_create, name='slotsRequestCreate'),
    url(r'^ranuras/(?P<pk>[0-9]+)/editar/$', views.slots_edit, name='slotsEdit'),
    url(r'^ranuras/(?P<pk>[0-9]+)/$', views.slots_detail, name='slotsDetail'),
    url(r'^api/ranura/(?P<pk_slot>[0-9]+)/borrar/$', views.APISlotDelete.as_view(), name="apiSlotsDelete"),#APIVIEW

    # Solicitudes
    url(r'^solicitudes/(?P<pk>[0-9]+)/$', views.request_detail, name='requestDetail'),
    url(r'^solicitudes/(?P<pk>[0-9]+)/borrar/$', views.request_delete, name='requestDelete'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/rechazar/$', views.APIrequest_reject.as_view(), name='requestReject'),
    url(r'^solicitudes/(?P<pk>[0-9]+)/editar/$', views.request_edit, name='requestEdit'),
    url(r'^solicitudes/crear/', views.request_create, name='requestCreate'),
    url(r'^solicitudes/', views.requests, name='requests'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/disponibilidad/$', views.ClassroomAvailability.as_view(),name='classroomAvailability'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/chequear_requisitos_de_sw/$', views.SWRequirementsCheck.as_view(),name='swRequirementsCheck'),

    # API Aulas
    url(r'^api/calendar/classrooms/$', views.AllClassrooms.as_view()),

    # API Clonar PC
    url(r'^api/pc/(?P<pk_pc>[0-9]+)/clonar/(?P<cantidad>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/$',views.ClonePCtoClassroom.as_view()),


    # API Slots
    url(r'^api/calendar/slots/(?P<day>[0-9]{2})/(?P<month>[0-9]{2})/(?P<year>[0-9]{4})/$', views.Slots_Reservation_Day.as_view()),
    url(r'^api/calendar/slots/$', views.Slots_Reservation.as_view()),
    url(r'^api/calendar/slots/(?P<start_day>[0-9]{2})/(?P<start_month>[0-9]{2})/(?P<start_year>[0-9]{4})/(?P<end_day>[0-9]{2})/(?P<end_month>[0-9]{2})/(?P<end_year>[0-9]{4})/(?P<user_id>[0-9]+)/$', views.Slots_Reservation_Range_Specific_User.as_view()),
    url(r'^api/calendar/slots/(?P<start_day>[0-9]{2})/(?P<start_month>[0-9]{2})/(?P<start_year>[0-9]{4})/(?P<end_day>[0-9]{2})/(?P<end_month>[0-9]{2})/(?P<end_year>[0-9]{4})/$', views.Slots_Reservation_Range.as_view()),


    # API update reservations' slots
    # ejemplo url: /api/reservations/1/update/subgroup/1/starttime/13:00/endtime/14:00/
    # url(r'^api/reservations/(?P<pk_reserva>[0-9]+)/update/subgroup/(?P<subgroup>[0-9]+)/starttime/(?P<start_time>[0-9]{2}:[0-9]{2})/endtime/(?P<end_time>[0-9]{2}:[0-9]{2})/$',views.Reservations_slot_subgroup_update.as_view()),
    url(r'^api/reservations/(?P<pk_reserva>[0-9]+)/editar/$', views.Reservations_slot_subgroup_update.as_view()),
    url(r'^api/requests/(?P<pk_solicitud>[0-9]+)/editar/$', views.Requests_slot_subgroup_update.as_view()),

    # Cuentas
    # path('accounts/', include('django.contrib.auth.urls')),
    # url(r'^core/signup/labuser/$', views.LabUserSignUpView.as_view(), name='labUserSignUp'),

    # hardcodeado (falta implementar funcionaldiad)
    url(r'^mensajes/', TemplateView.as_view(template_name='mensajes.html'), name='Mensajes'),

    path('core/', include('django.contrib.auth.urls')),
    ]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)

SysLab/core/forms.py
from django import forms
from .models import (
    PC, 
    PC_SO_SW, 
    Classroom, 
    SW, 
    SO, 
    Request, 
    Slots, 
    Reservation, 
    Establishment,
    Request_SW, 
    SW_Classroom
)

from django.forms import HiddenInput, inlineformset_factory, \
    DateTimeInput, modelformset_factory
# User types
from django.contrib.auth.forms import UserCreationForm
from .models import User


class EstablishmentForm(forms.ModelForm):
    class Meta(object):
        model = Establishment
        fields = ('name', 'address')
        labels = {
            'name': 'Nombre',
            'address': 'Dirección',
        }


class ClassroomForm(forms.ModelForm):
    class Meta(object):
        model = Classroom
        fields = ('number', 'address', 'floor', 'capacity', 'feature')
        labels = {
            'number': 'Número',
            'address': 'Establecimiento',
            'floor': 'Piso',
            'capacity': 'Capacidad',
            'feature': 'Caracteristicas',
        }


class SoForm(forms.ModelForm):
    class Meta(object):
        model = SO
        fields = ('name', 'description', 'virtualized')
        labels = {
            'name': 'Nombre',
            'description': 'Descripción',
            'virtualized': 'Virtualizado',
        }


class PcForm(forms.ModelForm):
    class Meta(object):
        model = PC
        fields = ('number', 'details', 'classroom', 'so')
        labels = {
            'number': 'Número',
            'details': 'Detalles',
            'classroom': 'Aula',
            'so': 'Sistema Operativo',
        }


class SlotsForm(forms.ModelForm):
    class Meta(object):
        model = Slots
        fields = ('day', 'start_time', 'end_time')
        labels = {
            'day': 'Día',
            'start_time': 'Inicio',
            'end_time': 'Fin',
        }


class SwForm(forms.ModelForm):
    class Meta(object):
        model = SW
        fields = ('name', 'description')
        labels = {
            'name': 'Nombre',
            'description': 'Descripción',
        }


class SwToClassroomForm(forms.ModelForm):
    class Meta(object):
        model = SW_Classroom
        fields = ('sw', 'classroom')
        labels = {
            'sw': 'Sw',
            'classroom': 'Aula'
        }


class PcSoSwForm(forms.ModelForm):
    class Meta(object):
        model = PC_SO_SW
        fields = ("pc_so", "sw")


class SwToPcForm(forms.ModelForm):
    class Meta(object):
        model = PC_SO_SW
        fields = ('sw',)

    sw = forms.ModelChoiceField(queryset=SW.objects.all())
    pc = forms.ModelChoiceField(queryset=PC.objects.all())
    so = forms.ModelChoiceField(queryset=SO.objects.none())

    # Valida que el so elegido sea uno de lo que tenga la PC
    # https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['so'].queryset = SO.objects.none()

        if 'so' in self.data:
            try:
                pc_id = int(self.data.get('pc'))
                self.fields['so'].queryset = SO.objects.filter(pc_so__pc_id=pc_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset


class RequestForm(forms.ModelForm):
    class Meta(object):
        model = Request
        exclude = ()


requestFormSet = inlineformset_factory(Request, Slots, form=RequestForm, extra=1)


class RequestFormOne(forms.ModelForm):
    until = forms.DateField(input_formats=["%d/%m/%Y"], required=False)
    repetition = forms.CharField(required=False)

    class Meta(object):
        model = Request
        fields = ('type', 'requirements', 'amountOfStudents', 'repetition', 'until', 'swsRequired', 'comments')
        labels = {
            'type': 'Tipo de Reserva',
            'requirements': 'Requerimientos de infraestructura (Opcional)',
            'amountOfStudents': 'Cantidad de estudiantes',
            'repetition': 'Repeticion',
            'until': 'Hasta',
            'swsRequired': 'Software solicitado',
            'comments': 'Comentarios',
        }


class RequestPeriodic(forms.ModelForm):
    until = forms.DateField(input_formats=["%d/%m/%Y"], required=False)
    repetition = forms.CharField(required=False)

    class Meta(object):
        model = Request
        fields = ('repetition', 'until')


class SlotRequest(forms.ModelForm):
    class Meta(object):
        model = Slots
        fields = ('day', 'start_time', 'end_time')
        labels = {
            'day': 'Día',
            'start_time': 'Hora de Inicio',
            'end_time': 'Hora de Fin',
        }
    
    start = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    end = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])


SlotsFormset = modelformset_factory(
    Slots,
    fields=('day', 'start_time', 'end_time', ),
    extra=1,
    widgets={'day': DateTimeInput(format="%d/%m/%y")}
)


class RequestToReservationForm(forms.ModelForm):
    class Meta(object):
        model = Reservation
        fields = ('name', 'classroom')
        labels = {
            'name': 'Nombre de reserva',
            'classroom': 'Aulas',
        }

    classroom = forms.ModelChoiceField(queryset=Classroom.objects.all())


class LabUserSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.labUser = True
        if commit:
            user.save()
        return user


RequestSwFormset = modelformset_factory(
    Request_SW,
    fields=('sw',),
    extra=1,
)

templates/Request/crear.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'sws' %}">Reservas</a>
        </li>
        <li class="breadcrumb-item active">Solicitud de Reserva</li>
    </ol>
{% endblock hilos %}

{% block content %}
<div class="card card-formAulas mx-auto">
    <div class="card-body">
        <div class="form-group">
            <div class="form-label-group text-center">
                <h5>Solicitud de Reserva de Laboratorio de Informatica</h5>
                <hr>
            </div>
        </div>
        <div>
        <form method="POST" id="formRequest">
            {% csrf_token %}

            <div id="div_id_type" class="form-group"><label for="id_type" class="col-form-label  requiredField">
                Tipo de Reserva<span class="asteriskField">*</span> </label>
                <div class="">
                    <select name="type" class="select form-control" id="id_type">
                        <option value="punctual" selected="">Puntual</option>
                        <option value="periodic">Periódica</option>
                    </select>
                </div>
            </div>

            <div id="div_id_repetition" class="form-group" style="display: none;">
                <label for="id_repetition" class="col-form-label  requiredField">
                    Repetir cada<span class="asteriskField">*</span>
                </label>
                <div class="">
                    <select name="repetition" class="select form-control" id="id_repetition">
                        <option value="weekly">Semana</option>
                        <option value="monthly">Mes</option>
                    </select>
                </div>
            </div>

            <div id="div_id_until" class="form-group" style="display: none;">
                <label for="id_until" class="col-form-label  requiredField">
                    Hasta el día<span class="asteriskField">*</span>
                </label>
                <div class="">
                    <input type="text" name="until" class="dateinput form-control" id="id_until">
                </div>
            </div>

            <div id="div_id_requirements" class="form-group">
                <label for="id_requirements" class="col-form-label  requiredField">
                    Requerimientos de infraestructura (Opcional)<span class="asteriskField">*</span>
                </label>
                <div class="">
                    <input type="text" name="requirements" value="aire acondicionado" maxlength="100"
                           class="textinput textInput form-control" required="" id="id_requirements">
                </div>
            </div>

            <div id="div_id_amountOfStudents" class="form-group">
                <label for="id_amountOfStudents" class="col-form-label  requiredField">
                    Cantidad de estudiantes<span class="asteriskField">*</span>
                </label>
                <div class="">
                    <input type="number" name="amountOfStudents" value="20" class="numberinput form-control"
                           required id="id_amountOfStudents" min="0">
                </div>
                <div class="invalid-feedback">La cantidad de alumnos debe ser un numero mayor a cero</div>
            </div>

            <!-- REQUERIMIENTOS DE SW -->
            <label for="id_amountOfStudents" class="col-form-label  requiredField">
                Software necesario<span class="asteriskField">*</span>
            </label>
            <div id="formSW" class="form-group">
                {{form.swsRequired}}
            </div>

            <div id="div_id_comments" class="form-group">
                <label for="id_comments" class="col-form-label requiredField">
                Comentarios</label>
                <div class="">
                    <textarea name="comments" placeholder="En caso de no encontrar el SW especificar acá" cols="40" rows="2" class="textarea form-control" id="id_comments" spellcheck="false"></textarea>
                </div>
            </div>

            <!-- SLOTS/PERIODOS -->
            <hr>

            <div id="formSlots">
                <input type="hidden" name="slots-TOTAL_FORMS" value="1" id="id_slots-TOTAL_FORMS">
                <input type="hidden" name="slots-INITIAL_FORMS" value="0" id="id_slots-INITIAL_FORMS">
                <input type="hidden" name="slots-MIN_NUM_FORMS" value="0" id="id_slots-MIN_NUM_FORMS">
                <input type="hidden" name="slots-MAX_NUM_FORMS" value="1000" id="id_slots-MAX_NUM_FORMS">

                <div class="multiField" id="slots-0">
                    <div id="div_id_slots-0-day" class="form-group">
                        <label for="id_slots-0-day" class="col-form-label requiredField">
                            Día<span class="asteriskField">*</span>
                        </label>
                        <div class="">
                            <input type="text" name="slots-0-day" class="dateinput form-control" id="id_slots-0-day" value="" required>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row d-flex justify-content-between">
                            <div class="col-sm-5 p-0">
                                <div id="div_id_slots-0-start_time" class="form-group">
                                    <label for="id_slots-0-start_time" class="col-form-label requiredField">
                                        Hora de inicio<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" name="slots-0-start_time" value="13:00" class="timeinput start form-control" id="id_slots-0-start_time" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-5 p-0">
                                <div id="div_id_slots-0-end_time" class="form-group">
                                    <label for="id_slots-0-end_time" class="col-form-label requiredField">
                                        Hora de fin<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" name="slots-0-end_time" value="14:00" class="timeinput end form-control" id="id_slots-0-end_time" required>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="slots-0-id" id="id_slots-0-id">
                </div>
            </div>

            <a class="btn btn-danger" href="javascript:void(0)" id="delete_slot" onclick="deleteForm('{{slots.prefix}}')" style="display: none;">Eliminar dia</a>
            <a class="btn btn-success" href="javascript:void(0)" id="new_slot" onclick="addDay()">Agregar nuevo dia </a>
            <hr>
            <div class="form-group">
                <button id="createBTN" onclick="submitForm()" type="submit" class="btn btn-primary btn-block" >
                    <span id="btnSpinner" class="spinner-border spinner-border-sm" role="status" style="display: none"></span>
                    <span id="btnText">Crear</span>
                </button>
            </div>
        </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    function submitForm() {
        let form = document.getElementById('formRequest');

        if (!form.checkValidity()) {
            return false;
        }

        $("#createBTN").attr("disabled", true);
        $("#btnText").text("Creando...");
        $("#btnSpinner").show();
        form.submit();
    }
 
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+)');
        var replacement = prefix + '-' + ndx; if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }

    function cloneMore(selector, prefix, index) {
        var newElement = $('#'+ selector +'>.multiField:first').clone(true);
        var total = $('#id_' + prefix + '-TOTAL_FORMS').val();

        newElement.find(':input').each(function() {
            var name = $(this).attr('name');
            if(name) {
                name = name.replace('-0-', '-' + index + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            }
        });
        newElement.attr('id', `${prefix}-`+index);
        $(`#${selector}`).append(newElement);
        if (prefix === 'slots') {
            document.getElementById(`id_slots-${index}-day`).required = false;
            document.getElementById(`id_slots-${index}-start_time`).required = false;
            document.getElementById(`id_slots-${index}-end_time`).required = false;
            $(`#${prefix}-${index}`).hide();
        }

        return false;
    }

    // Agregar un SW a la solicitud
    function addNewForm(prefix) {
        let total = $('#id_sw_requirements-TOTAL_FORMS').val();
        cloneMore('formSW', prefix, total);
        $('#id_sw_requirements-TOTAL_FORMS').val(parseInt(total) + 1);
        $('#delete_sw_requirement').show();
    }

    // Agregar un nuevo dia
    function addDay() {
        let total = $('#id_slots-TOTAL_FORMS').val();
        $(`#slots-${total}`).show();
        document.getElementById(`id_slots-${total}-day`).setAttribute('required', '');
        document.getElementById(`id_slots-${total}-start_time`).setAttribute('required', '');
        document.getElementById(`id_slots-${total}-end_time`).setAttribute('required', '');
        $('#id_slots-TOTAL_FORMS').val(parseInt(total) + 1);
        $('#delete_slot').show();
    }

    // Eliminar dia o requerimiento de SW
    function deleteForm(prefix) {
        let selector;
        let total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());

        if (total === 1) return false;

        if(prefix=='sw_requirements'){
            selector = document.getElementById("delete_sw_requirement");
            $(`#${prefix}-${total - 1}`).remove();
        }
        if(prefix=='slots'){
            selector = document.getElementById("delete_slot");
            document.getElementById(`id_slots-${total - 1}-day`).required = false;
            document.getElementById(`id_slots-${total - 1}-start_time`).required = false;
            document.getElementById(`id_slots-${total - 1}-end_time`).required = false;
            $(`#${prefix}-${total - 1}`).hide();
        }

        if (total === 2) {
            $(selector).hide();
        }

        $('#id_' + prefix + '-TOTAL_FORMS').val(total-1);
    }

    // Cambiar tipo de solicitud (puntual o periodica)
    let select_type = document.getElementById("id_type");
    select_type.onchange = function () {
        let request_type = select_type.value;

        if (request_type === 'periodic') {
            $('#div_id_repetition').show();
            $('#id_repetition').attr('required', '');
            $('#div_id_until').show();
            $('#id_until').attr('required', '');
        }
        else {
            $('#div_id_repetition').hide();
            $('#id_repetition').removeAttr('required');
            $('#div_id_until').hide();
            $('#id_until').removeAttr('required', '');
        }
    };

    function iniDatePicker() {
        let total = $('#id_slots-TOTAL_FORMS').val();

        while (total < 11) {
            cloneMore('formSlots', 'slots', total);
            total++;
        }
    }

    $(document).ready(function(){
        $('#div_id_repetition').hide();
        $('#div_id_until').hide();

        iniDatePicker();

        $('.dateinput').datepicker({
            'format': 'dd/mm/yyyy',
            'autoclose': true,
            language: 'es',
            'minDate': new Date(),
            onRenderCell: function (date, cellType) {
                if (cellType === 'day') {
                    let day = date.getDay(),
                        isDisabled = day === 0;
                    return {
                        disabled: isDisabled
                    }
                }
            }
        });
    });
</script>
<script type="text/javascript" src="{% static 'js/fn.chosen.js' %}"></script>
<script type="text/javascript" src="{% static 'js/fn.timepicker.js' %}"></script>
{% endblock content %}

templates/Request/mostrarReserva.html
<div class="card">
    <h5 class="card-header text-center">Reserva</h5>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <h5>Reserva asociada: <a href={% url 'reservationDetail' reservation.id %}>Reserva N° {{reservation.id}}</a>
                </h5>
                <div class="text-right">
                    <a href="{% url 'reservationEdit' reservation.id %}" class="btn btn-primary">Editar</a>
                    <a href="{% url 'reservationDelete' reservation.id %}" class="btn btn-danger">Eliminar</a>
                </div>
            </div>
        </div>
    </div>
</div>