SysLab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from django.conf import settings
from django.conf.urls.static import static
from .core import views
from django.contrib.auth import views as auth_views

from rest_framework.urlpatterns import format_suffix_patterns

router = DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'group', views.GroupViewSet)
router.register(r'classroom', views.ClassroomViewSet)
router.register(r'request', views.RequestViewSet)
router.register(r'so', views.SOViewSet)
router.register(r'pc', views.PCViewSet)
router.register(r'pc_so_sw', views.PC_SO_SWViewSet)
router.register(r'sw', views.SWViewSet)
# The API URLs are now determined automatically by the router.

urlpatterns = [

    # admin y api
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # login
    url(r'^index/', views.index , name='index'),

    # index, login y logout
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # se puede hacer una logout view pero por ahora redirije a login nomas, en settings esta configurado
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    # Aulas
    url(r'^aulas/(?P<pk>[0-9]+)/$', views.classroom_detail, name='aulaDetail'),
    url(r'^aulas/(?P<pk>[0-9]+)/borrar/$', views.classroom_delete, name='aulaDelete'),
    url(r'^aulas/(?P<pk>[0-9]+)/editar/$', views.classroom_edit, name='aulaEdit'),
    url(r'^aulas/crear/', views.classroom_create, name='aulaCreate'),
    url(r'^aulas/', views.classrooms, name='aulas'),

    # Establecimientos
    url(r'^establecimientos/(?P<pk>[0-9]+)/$', views.establishment_detail, name='establecimientoDetail'),
    url(r'^establecimientos/(?P<pk>[0-9]+)/borrar/$', views.establishment_delete, name='establecimientoDelete'),
    url(r'^establecimientos/(?P<pk>[0-9]+)/editar/$', views.establishment_edit, name='establecimientoEdit'),
    url(r'^establecimientos/crear/', views.establishment_create, name='establecimientoCreate'),
    url(r'^establecimientos/', views.establishments, name='establecimientos'),

    # SOs
    url(r'^sos/(?P<pk>[0-9]+)/$', views.so_detail, name='soDetail'),
    url(r'^sos/(?P<pk>[0-9]+)/borrar/$', views.so_delete, name='soDelete'),
    url(r'^sos/(?P<pk>[0-9]+)/editar/$', views.so_edit, name='soEdit'),
    url(r'^sos/crear/', views.so_create, name='soCreate'),
    url(r'^sos/', views.sos, name='sos'),
    url(r'^ajax/so/', views.so_by_pc, name='ajax_so_by_pc'),

    # PCs
    url(r'^pcs/(?P<pk>[0-9]+)/$', views.pc_detail, name='pcDetail'),
    url(r'^pcs/(?P<pk>[0-9]+)/borrar/$', views.pc_delete, name='pcDelete'),
    url(r'^pcs/(?P<pk>[0-9]+)/editar/$', views.pc_edit, name='pcEdit'),
    url(r'^pcs/crear/', views.pc_create, name='pcCreate'),
    url(r'^pcs/(?P<pk>[0-9]+)/clonar/$', views.pc_clone, name='pcClone'),
    url(r'^pcs/$', views.pcs, name='pcs'),

    # SW
    url(r'^sws/(?P<pk>[0-9]+)/$', views.sw_detail, name='swDetail'),
    url(r'^sws/(?P<pk>[0-9]+)/borrar/$', views.sw_delete, name='swDelete'),
    url(r'^sws/(?P<pk>[0-9]+)/editar/$', views.sw_edit, name='swEdit'),
    url(r'^sws/crear/', views.sw_create, name='swCreate'),
    url(r'^sws/asignar/pc/', views.sw_assign, name='swAssign'),
    url(r'^sws/asignaciones/(?P<pk>[0-9]+)/borrar/$', views.sw_assignment_delete, name='swAssignmentDelete'),
    url(r'^sws/asignaciones/', views.sw_assignments, name='swAssignments'),
    url(r'^sws/asignar/aula/', views.sw_so_classroom_assignment, name='swSOClassroomAssignment'),
    url(r'^sws/', views.sws, name='sws'),

    # Reserva
    url(r'^reservas/$', views.reservations, name='reservations'),
    url(r'^reservas/listado/$', views.reservations_listado, name='reservations_listado'),
    url(r'^reservas/(?P<pk>[0-9]+)/editar/$', views.reservation_edit, name='reservationEdit'),
    url(r'^reservas/(?P<pk>[0-9]+)/$', views.reservation_detail, name='reservationDetail'),
    url(r'^reservas/(?P<pk>[0-9]+)/borrar/$', views.reservation_delete, name='reservationDelete'),

    # Slots
    url(r'^ranuras/crear/reserva/(?P<pk_reserva>[0-9]+)/$', views.slots_reservation_create, name='slotsReservationCreate'),
    url(r'^ranuras/crear/solicitud/(?P<pk_solicitud>[0-9]+)/$',views.slots_request_create, name='slotsRequestCreate'),
    url(r'^ranuras/(?P<pk>[0-9]+)/editar/$', views.slots_edit, name='slotsEdit'),
    url(r'^ranuras/(?P<pk>[0-9]+)/$', views.slots_detail, name='slotsDetail'),
    url(r'^api/ranura/(?P<pk_slot>[0-9]+)/borrar/$', views.APISlotDelete.as_view(), name="apiSlotsDelete"),#APIVIEW

    # Solicitudes
    url(r'^solicitudes/(?P<pk>[0-9]+)/$', views.request_detail, name='requestDetail'),
    url(r'^solicitudes/(?P<pk>[0-9]+)/borrar/$', views.request_delete, name='requestDelete'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/rechazar/$', views.APIrequest_reject.as_view(), name='requestReject'),
    url(r'^solicitudes/(?P<pk>[0-9]+)/editar/$', views.request_edit, name='requestEdit'),
    url(r'^solicitudes/crear/', views.request_create, name='requestCreate'),
    url(r'^solicitudes/', views.requests, name='requests'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/disponibilidad/$', views.ClassroomAvailability.as_view(),name='classroomAvailability'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/chequear_requisitos_de_sw/$', views.SWRequirementsCheck.as_view(),name='swRequirementsCheck'),

    # API Aulas
    url(r'^api/calendar/classrooms/$', views.AllClassrooms.as_view()),

    # API Clonar PC
    url(r'^api/pc/(?P<pk_pc>[0-9]+)/clonar/(?P<cantidad>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/$',views.ClonePCtoClassroom.as_view()),


    # API Slots
    url(r'^api/calendar/slots/(?P<day>[0-9]{2})/(?P<month>[0-9]{2})/(?P<year>[0-9]{4})/$', views.Slots_Reservation_Day.as_view()),
    url(r'^api/calendar/slots/$', views.Slots_Reservation.as_view()),
    url(r'^api/calendar/slots/(?P<start_day>[0-9]{2})/(?P<start_month>[0-9]{2})/(?P<start_year>[0-9]{4})/(?P<end_day>[0-9]{2})/(?P<end_month>[0-9]{2})/(?P<end_year>[0-9]{4})/(?P<user_id>[0-9]+)/$', views.Slots_Reservation_Range_Specific_User.as_view()),
    url(r'^api/calendar/slots/(?P<start_day>[0-9]{2})/(?P<start_month>[0-9]{2})/(?P<start_year>[0-9]{4})/(?P<end_day>[0-9]{2})/(?P<end_month>[0-9]{2})/(?P<end_year>[0-9]{4})/$', views.Slots_Reservation_Range.as_view()),


    # API update reservations' slots
    # ejemplo url: /api/reservations/1/update/subgroup/1/starttime/13:00/endtime/14:00/
    # url(r'^api/reservations/(?P<pk_reserva>[0-9]+)/update/subgroup/(?P<subgroup>[0-9]+)/starttime/(?P<start_time>[0-9]{2}:[0-9]{2})/endtime/(?P<end_time>[0-9]{2}:[0-9]{2})/$',views.Reservations_slot_subgroup_update.as_view()),
    url(r'^api/reservations/(?P<pk_reserva>[0-9]+)/editar/$', views.Reservations_slot_subgroup_update.as_view()),
    url(r'^api/requests/(?P<pk_solicitud>[0-9]+)/editar/$', views.Requests_slot_subgroup_update.as_view()),

    # Cuentas
    # path('accounts/', include('django.contrib.auth.urls')),
    # url(r'^core/signup/labuser/$', views.LabUserSignUpView.as_view(), name='labUserSignUp'),

    # hardcodeado (falta implementar funcionaldiad)
    url(r'^mensajes/', TemplateView.as_view(template_name='mensajes.html'), name='Mensajes'),

    path('core/', include('django.contrib.auth.urls')),
    ]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)

SysLab/core/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
import datetime
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


# implementacion basada en: https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html


class User(AbstractUser):
    # bandera que indica el tipo de usuario
    is_admin = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    is_becario = models.BooleanField(default=False)

    # USER_TYPE_CHOICES = (
    #   (1, 'student'),
    #   (2, 'teacher'),
    #   (3, 'secretary'),
    #   (4, 'supervisor'),
    #   (5, 'admin'),
    # )

    # user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES)


class Establishment(models.Model):
    name = models.CharField(default='', max_length=100)
    address = models.CharField(default='', max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('establecimientoDetail', kwargs={"pk": self.id})


class Classroom(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    number = models.CharField(max_length=5, unique=True)
    floor = models.PositiveIntegerField(default=0)
    address = models.ForeignKey(Establishment, on_delete=models.CASCADE)

    capacity = models.PositiveIntegerField(default=0)
    feature = models.CharField(default='', max_length=100, null=True, blank=True)

    # owner = models.ForeignKey('auth.User', default='', related_name='classrooms', on_delete=models.CASCADE)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return (f'{self.number}')

    def get_absolute_url(self):
        return reverse('aulaDetail', kwargs={"pk": self.id})


class SO(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now=True)
    virtualized = models.BooleanField(
        verbose_name="Virtualizado", default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('soDetail', kwargs={"pk": self.id})


class PC(models.Model):
    number = models.PositiveIntegerField()
    details = models.CharField(max_length=300)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    so = models.ManyToManyField(SO, through='PC_SO', )
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['number', 'classroom']
    
    def __str__(self):
        return (f'{self.number} [Aula: {self.classroom}]')

    def get_absolute_url(self):
        return reverse('pcDetail', kwargs={"pk": self.id})


class PC_SO(models.Model):
    pc = models.ForeignKey(PC, on_delete=models.CASCADE)
    so = models.ForeignKey(SO, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['pc', 'so']

    def __str__(self):
        return str(self.pc) + " " + str(self.so)


class SW(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=300)
    pc_so = models.ManyToManyField(PC_SO, through='PC_SO_SW',)

    def get_absolute_url(self):
        return reverse('swDetail', kwargs={"pk": self.id})

    def __str__(self):
        return self.name

# No vamos a utilizar este modelo, vamos a unir pc a aula y pc a sw.
class SW_Classroom(models.Model):
    sw = models.ForeignKey(SW, verbose_name=u'SW', on_delete=models.CASCADE)
    classroom = models.ForeignKey(
        Classroom, verbose_name=u'Classroom', on_delete=models.CASCADE)

    def __str__(self):
        return self.sw


class PC_SO_SW(models.Model):
    pc_so = models.ForeignKey(
        PC_SO, verbose_name=u'PC', on_delete=models.CASCADE)
    sw = models.ForeignKey(SW, verbose_name=u'SW', on_delete=models.CASCADE)

    class Meta:
        unique_together = ['pc_so', 'sw']

    def __str__(self):
        return str(self.pc_so) + " " + str(self.sw)


class Request(models.Model):
    # se reemplaza "owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)" por:
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    requirements = models.CharField(
        default='aire acondicionado', max_length=100)
    # new: recien creada, aun puede ser editarse
    # pending: pendiente de aprobación
    # rejected: rechazada
    # approved: aprobada
    STATUS_CHOICES = (('new', 'nueva'), ('deletedReservation', 'reserva elmininada'),
                      ('approved', 'aprobada'), ('rejected', 'rechazada'))
    status = models.CharField(choices=STATUS_CHOICES,
                              default='new', max_length=100)
    CHOICES = (('punctual', 'Puntual'), ('periodic', 'Periódica'))
    type = models.CharField(
        choices=CHOICES, max_length=20, default='punctual')
    # Frecuency of the repetition
    CHOICES_REP = (('weekly', 'Semana'), ('monthly', 'Mes'))
    repetition = models.CharField(
        choices=CHOICES_REP, max_length=20, null=True)
    # Last day of a reservation
    until = models.DateField(verbose_name="Hasta el día", null=True)
    amountOfStudents = models.PositiveIntegerField(
        verbose_name=u'cantidad_de_pcs', default=20, null=False)
    swsRequired = models.ManyToManyField(
        SW, verbose_name=u"software(s)_soliciado(s)", through="Request_SW", blank=True)
    comments = models.TextField(blank=True, null=True)

    def __str__(self):
        # return 'req: ' + str(self.id)
        return 'id_solicitud: {} ; usuario_solicitante: {}'.format(self.id, self.owner)


class Request_SW(models.Model):
    request = models.ForeignKey(
        Request, verbose_name=u"solicitud", on_delete=models.CASCADE)
    sw = models.ForeignKey(
        SW, verbose_name=u"software solicitado", on_delete=models.CASCADE)

    def __str__(self):
        return 'request: ' + str(self.request) + " sw: " + str(self.sw)


class Reservation(models.Model):
    name = models.CharField(max_length=80)
    classroom = models.ForeignKey(
        Classroom, verbose_name=u"Aula", on_delete=models.CASCADE)
    request = models.OneToOneField(Request, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


HOY = datetime.datetime.now().strftime("%d/%m/%Y")


class Slots(models.Model):
    request = models.ForeignKey(Request, on_delete=models.CASCADE)
    reservation = models.ForeignKey(
        Reservation, on_delete=models.SET_NULL, blank=True, null=True)
    day = models.DateField(default=HOY, verbose_name="Día")
    start_time = models.TimeField(
        default="13:00", verbose_name="Hora de inicio")
    end_time = models.TimeField(default="14:00", verbose_name="Hora de fin")

    class Meta:
        ordering = ('day',)

    def __str__(self):
        return (f'Request: {self.request} Day: {self.day} Start: {seld.start_time} End: {self.end_time}')

    def clean(self):
        if self.start_time > self.end_time:
            raise ValidationError(_('La hora de inicio debe ser previa a la hora de fin'))

templates/Slots/crear.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        {% if reservation.id %}
        <li class="breadcrumb-item active">
            <a href="{% url 'reservations_listado' %}">Reservas</a>
        </li>
        <li class="breadcrumb-item active">
            <a href="{% url 'reservationDetail' reservation.id %}">Reserva {{ reservation.id }}</a>
        </li>
        {% endif %}
        {% if instance.number %}
            <li class="breadcrumb-item active">Editar Ranura {{ instance.number }}</li>
        {% else %}
            <li class="breadcrumb-item active">Crear Ranura</li>
        {% endif %}
    </ol>
{% endblock hilos %}

{% block content %}
    <div class="card card-formAulas mx-auto">
        <div class="card-body">
            <div class="form-group">
                <div class="form-label-group text-center">
                    {% if instance.number %}
                        <h5>Editar Ranura {{ instance.number }}</h5>
                    {% else %}
                        <h5>Crear Ranura</h5>
                    {% endif %}
                    <hr>
                </div>
            </div>
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Guardar</button>
                </div>
            </form>

        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.dateinput').datepicker({
                'format': 'dd/mm/yyyy',
                'autoclose': true,
                language: 'es',
                'minDate': new Date(),
                onRenderCell: function (date, cellType) {
                    if (cellType === 'day') {
                        let day = date.getDay(),
                            isDisabled = day === 0;
                        return {
                            disabled: isDisabled
                        }
                    }
                }
            });
        });
    </script>
    <script type="text/javascript" src="{% static 'js/fn.timepicker.js' %}"></script>
{% endblock content %}

templates/Slots/editar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static%}

{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li class="breadcrumb-item active">
            <b>Ranuras</b>
        </li>
        <li class="breadcrumb-item active">Ranura: <b>{{instance.id}}</b> </li>
    </ol>
{% endblock hilos %}

{% block content %}
    <div class="card card-formAulas mx-auto">
        <div class="card-body">
            <div class="form-group">
                <div class="form-label-group text-center">
                        <h5>Editar Ranura</h5>
                    <hr>
                </div>
            </div>
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="form-group">
                    <button type="submit" class="save btn btn-primary btn-block">Guardar</button>
                    <button onclick="borrarSlot({{instance.id}});" class="save btn btn-danger btn-block">Eliminar</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        async function borrarSlot(slot_pk){
            url_to_fectch = `/api/ranura/${slot_pk}/borrar/`;
            await fetch(url_to_fectch).catch(err => console.error(err));
            document.location.replace(document.referrer);
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#id_day').datepicker({
                'format': 'dd/mm/yyyy',
                'autoclose': true,
                language: 'es',
                'minDate': new Date(),
                onRenderCell: function (date, cellType) {
                    if (cellType === 'day') {
                        let day = date.getDay(),
                            isDisabled = day === 0;
                        return {
                            disabled: isDisabled
                        }
                    }
                }
            });
        });
    </script>
    <script type="text/javascript" src="{% static 'js/fn.timepicker.js' %}"></script>
{% endblock content %}

templates/Slots/ver.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li class="breadcrumb-item active">
            <b>Ranuras</b>
        </li>
        <li class="breadcrumb-item active">Ranura: <b>{{instance.id}}</b> </li>
    </ol>
{% endblock hilos %}
<!-- Contenido de la Página-->
{% block content %}
    <div class="card card-formAulas mx-auto">
        <h5 class="card-header"><b>Ranura:</b> {{instance.id}} </h5>
        <div class="card-body">
            
            <div class="form-group">
                <div class="form-label-group">
                    <b>Solicitud de reserva:</b> {{instance.request.id}}
                </div>
            </div>
            <div class="form-group">
                <div class="form-label-group">
                    <b>Reserva asociada:</b> {{instance.reservation.id}}
                </div>
            </div>
            <div class="form-group">
                <div class="form-label-group">
                    <b>Día:</b> {{instance.day}}
                </div>
            </div>
            <div class="form-group">
                <div class="form-label-group">
                    <b>Hora de inicio:</b> {{instance.start_time}}
                </div>
            </div>
            <div class="form-group">
                <div class="form-label-group">
                    <b>Hora de fin:</b> {{instance.end_time}}
                </div>
            </div>
            {% if user.is_admin %}
            <div class="form-group">
                <a href="{% url 'slotsEdit' instance.id %}" class="btn btn-primary btn-block">Editar</a>
                <a href="{% url 'apiSlotsDelete' instance.id %}" class="btn btn-danger btn-block">Eliminar</a>
            </div>
            {% endif %}
         </div>
    </div>

{% endblock content %}