SysLab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from django.conf import settings
from django.conf.urls.static import static
from .core import views
from django.contrib.auth import views as auth_views

from rest_framework.urlpatterns import format_suffix_patterns

router = DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'group', views.GroupViewSet)
router.register(r'classroom', views.ClassroomViewSet)
router.register(r'request', views.RequestViewSet)
router.register(r'so', views.SOViewSet)
router.register(r'pc', views.PCViewSet)
router.register(r'pc_so_sw', views.PC_SO_SWViewSet)
router.register(r'sw', views.SWViewSet)
# The API URLs are now determined automatically by the router.

urlpatterns = [

    # admin y api
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # login
    url(r'^index/', views.index , name='index'),

    # index, login y logout
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # se puede hacer una logout view pero por ahora redirije a login nomas, en settings esta configurado
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    # Aulas
    url(r'^aulas/(?P<pk>[0-9]+)/$', views.classroom_detail, name='aulaDetail'),
    url(r'^aulas/(?P<pk>[0-9]+)/borrar/$', views.classroom_delete, name='aulaDelete'),
    url(r'^aulas/(?P<pk>[0-9]+)/editar/$', views.classroom_edit, name='aulaEdit'),
    url(r'^aulas/crear/', views.classroom_create, name='aulaCreate'),
    url(r'^aulas/', views.classrooms, name='aulas'),

    # Establecimientos
    url(r'^establecimientos/(?P<pk>[0-9]+)/$', views.establishment_detail, name='establecimientoDetail'),
    url(r'^establecimientos/(?P<pk>[0-9]+)/borrar/$', views.establishment_delete, name='establecimientoDelete'),
    url(r'^establecimientos/(?P<pk>[0-9]+)/editar/$', views.establishment_edit, name='establecimientoEdit'),
    url(r'^establecimientos/crear/', views.establishment_create, name='establecimientoCreate'),
    url(r'^establecimientos/', views.establishments, name='establecimientos'),

    # SOs
    url(r'^sos/(?P<pk>[0-9]+)/$', views.so_detail, name='soDetail'),
    url(r'^sos/(?P<pk>[0-9]+)/borrar/$', views.so_delete, name='soDelete'),
    url(r'^sos/(?P<pk>[0-9]+)/editar/$', views.so_edit, name='soEdit'),
    url(r'^sos/crear/', views.so_create, name='soCreate'),
    url(r'^sos/', views.sos, name='sos'),
    url(r'^ajax/so/', views.so_by_pc, name='ajax_so_by_pc'),

    # PCs
    url(r'^pcs/(?P<pk>[0-9]+)/$', views.pc_detail, name='pcDetail'),
    url(r'^pcs/(?P<pk>[0-9]+)/borrar/$', views.pc_delete, name='pcDelete'),
    url(r'^pcs/(?P<pk>[0-9]+)/editar/$', views.pc_edit, name='pcEdit'),
    url(r'^pcs/crear/', views.pc_create, name='pcCreate'),
    url(r'^pcs/(?P<pk>[0-9]+)/clonar/$', views.pc_clone, name='pcClone'),
    url(r'^pcs/$', views.pcs, name='pcs'),

    # SW
    url(r'^sws/(?P<pk>[0-9]+)/$', views.sw_detail, name='swDetail'),
    url(r'^sws/(?P<pk>[0-9]+)/borrar/$', views.sw_delete, name='swDelete'),
    url(r'^sws/(?P<pk>[0-9]+)/editar/$', views.sw_edit, name='swEdit'),
    url(r'^sws/crear/', views.sw_create, name='swCreate'),
    url(r'^sws/asignar/pc/', views.sw_assign, name='swAssign'),
    url(r'^sws/asignaciones/(?P<pk>[0-9]+)/borrar/$', views.sw_assignment_delete, name='swAssignmentDelete'),
    url(r'^sws/asignaciones/', views.sw_assignments, name='swAssignments'),
    url(r'^sws/asignar/aula/', views.sw_so_classroom_assignment, name='swSOClassroomAssignment'),
    url(r'^sws/', views.sws, name='sws'),

    # Reserva
    url(r'^reservas/$', views.reservations, name='reservations'),
    url(r'^reservas/listado/$', views.reservations_listado, name='reservations_listado'),
    url(r'^reservas/(?P<pk>[0-9]+)/editar/$', views.reservation_edit, name='reservationEdit'),
    url(r'^reservas/(?P<pk>[0-9]+)/$', views.reservation_detail, name='reservationDetail'),
    url(r'^reservas/(?P<pk>[0-9]+)/borrar/$', views.reservation_delete, name='reservationDelete'),

    # Slots
    url(r'^ranuras/crear/reserva/(?P<pk_reserva>[0-9]+)/$', views.slots_reservation_create, name='slotsReservationCreate'),
    url(r'^ranuras/crear/solicitud/(?P<pk_solicitud>[0-9]+)/$',views.slots_request_create, name='slotsRequestCreate'),
    url(r'^ranuras/(?P<pk>[0-9]+)/editar/$', views.slots_edit, name='slotsEdit'),
    url(r'^ranuras/(?P<pk>[0-9]+)/$', views.slots_detail, name='slotsDetail'),
    url(r'^api/ranura/(?P<pk_slot>[0-9]+)/borrar/$', views.APISlotDelete.as_view(), name="apiSlotsDelete"),#APIVIEW

    # Solicitudes
    url(r'^solicitudes/(?P<pk>[0-9]+)/$', views.request_detail, name='requestDetail'),
    url(r'^solicitudes/(?P<pk>[0-9]+)/borrar/$', views.request_delete, name='requestDelete'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/rechazar/$', views.APIrequest_reject.as_view(), name='requestReject'),
    url(r'^solicitudes/(?P<pk>[0-9]+)/editar/$', views.request_edit, name='requestEdit'),
    url(r'^solicitudes/crear/', views.request_create, name='requestCreate'),
    url(r'^solicitudes/', views.requests, name='requests'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/disponibilidad/$', views.ClassroomAvailability.as_view(),name='classroomAvailability'),
    url(r'^api/solicitudes/(?P<pk_solicitud>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/chequear_requisitos_de_sw/$', views.SWRequirementsCheck.as_view(),name='swRequirementsCheck'),

    # API Aulas
    url(r'^api/calendar/classrooms/$', views.AllClassrooms.as_view()),

    # API Clonar PC
    url(r'^api/pc/(?P<pk_pc>[0-9]+)/clonar/(?P<cantidad>[0-9]+)/aula/(?P<pk_aula>[0-9]+)/$',views.ClonePCtoClassroom.as_view()),


    # API Slots
    url(r'^api/calendar/slots/(?P<day>[0-9]{2})/(?P<month>[0-9]{2})/(?P<year>[0-9]{4})/$', views.Slots_Reservation_Day.as_view()),
    url(r'^api/calendar/slots/$', views.Slots_Reservation.as_view()),
    url(r'^api/calendar/slots/(?P<start_day>[0-9]{2})/(?P<start_month>[0-9]{2})/(?P<start_year>[0-9]{4})/(?P<end_day>[0-9]{2})/(?P<end_month>[0-9]{2})/(?P<end_year>[0-9]{4})/(?P<user_id>[0-9]+)/$', views.Slots_Reservation_Range_Specific_User.as_view()),
    url(r'^api/calendar/slots/(?P<start_day>[0-9]{2})/(?P<start_month>[0-9]{2})/(?P<start_year>[0-9]{4})/(?P<end_day>[0-9]{2})/(?P<end_month>[0-9]{2})/(?P<end_year>[0-9]{4})/$', views.Slots_Reservation_Range.as_view()),


    # API update reservations' slots
    # ejemplo url: /api/reservations/1/update/subgroup/1/starttime/13:00/endtime/14:00/
    # url(r'^api/reservations/(?P<pk_reserva>[0-9]+)/update/subgroup/(?P<subgroup>[0-9]+)/starttime/(?P<start_time>[0-9]{2}:[0-9]{2})/endtime/(?P<end_time>[0-9]{2}:[0-9]{2})/$',views.Reservations_slot_subgroup_update.as_view()),
    url(r'^api/reservations/(?P<pk_reserva>[0-9]+)/editar/$', views.Reservations_slot_subgroup_update.as_view()),
    url(r'^api/requests/(?P<pk_solicitud>[0-9]+)/editar/$', views.Requests_slot_subgroup_update.as_view()),

    # Cuentas
    # path('accounts/', include('django.contrib.auth.urls')),
    # url(r'^core/signup/labuser/$', views.LabUserSignUpView.as_view(), name='labUserSignUp'),

    # hardcodeado (falta implementar funcionaldiad)
    url(r'^mensajes/', TemplateView.as_view(template_name='mensajes.html'), name='Mensajes'),

    path('core/', include('django.contrib.auth.urls')),
    ]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)

SysLab/core/forms.py
from django import forms
from .models import (
    PC, 
    PC_SO_SW, 
    Classroom, 
    SW, 
    SO, 
    Request, 
    Slots, 
    Reservation, 
    Establishment,
    Request_SW, 
    SW_Classroom
)

from django.forms import HiddenInput, inlineformset_factory, \
    DateTimeInput, modelformset_factory
# User types
from django.contrib.auth.forms import UserCreationForm
from .models import User


class EstablishmentForm(forms.ModelForm):
    class Meta(object):
        model = Establishment
        fields = ('name', 'address')
        labels = {
            'name': 'Nombre',
            'address': 'Dirección',
        }


class ClassroomForm(forms.ModelForm):
    class Meta(object):
        model = Classroom
        fields = ('number', 'address', 'floor', 'capacity', 'feature')
        labels = {
            'number': 'Número',
            'address': 'Establecimiento',
            'floor': 'Piso',
            'capacity': 'Capacidad',
            'feature': 'Caracteristicas',
        }


class SoForm(forms.ModelForm):
    class Meta(object):
        model = SO
        fields = ('name', 'description', 'virtualized')
        labels = {
            'name': 'Nombre',
            'description': 'Descripción',
            'virtualized': 'Virtualizado',
        }


class PcForm(forms.ModelForm):
    class Meta(object):
        model = PC
        fields = ('number', 'details', 'classroom', 'so')
        labels = {
            'number': 'Número',
            'details': 'Detalles',
            'classroom': 'Aula',
            'so': 'Sistema Operativo',
        }


class SlotsForm(forms.ModelForm):
    class Meta(object):
        model = Slots
        fields = ('day', 'start_time', 'end_time')
        labels = {
            'day': 'Día',
            'start_time': 'Inicio',
            'end_time': 'Fin',
        }


class SwForm(forms.ModelForm):
    class Meta(object):
        model = SW
        fields = ('name', 'description')
        labels = {
            'name': 'Nombre',
            'description': 'Descripción',
        }


class SwToClassroomForm(forms.ModelForm):
    class Meta(object):
        model = SW_Classroom
        fields = ('sw', 'classroom')
        labels = {
            'sw': 'Sw',
            'classroom': 'Aula'
        }


class PcSoSwForm(forms.ModelForm):
    class Meta(object):
        model = PC_SO_SW
        fields = ("pc_so", "sw")


class SwToPcForm(forms.ModelForm):
    class Meta(object):
        model = PC_SO_SW
        fields = ('sw',)

    sw = forms.ModelChoiceField(queryset=SW.objects.all())
    pc = forms.ModelChoiceField(queryset=PC.objects.all())
    so = forms.ModelChoiceField(queryset=SO.objects.none())

    # Valida que el so elegido sea uno de lo que tenga la PC
    # https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['so'].queryset = SO.objects.none()

        if 'so' in self.data:
            try:
                pc_id = int(self.data.get('pc'))
                self.fields['so'].queryset = SO.objects.filter(pc_so__pc_id=pc_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset


class RequestForm(forms.ModelForm):
    class Meta(object):
        model = Request
        exclude = ()


requestFormSet = inlineformset_factory(Request, Slots, form=RequestForm, extra=1)


class RequestFormOne(forms.ModelForm):
    until = forms.DateField(input_formats=["%d/%m/%Y"], required=False)
    repetition = forms.CharField(required=False)

    class Meta(object):
        model = Request
        fields = ('type', 'requirements', 'amountOfStudents', 'repetition', 'until', 'swsRequired', 'comments')
        labels = {
            'type': 'Tipo de Reserva',
            'requirements': 'Requerimientos de infraestructura (Opcional)',
            'amountOfStudents': 'Cantidad de estudiantes',
            'repetition': 'Repeticion',
            'until': 'Hasta',
            'swsRequired': 'Software solicitado',
            'comments': 'Comentarios',
        }


class RequestPeriodic(forms.ModelForm):
    until = forms.DateField(input_formats=["%d/%m/%Y"], required=False)
    repetition = forms.CharField(required=False)

    class Meta(object):
        model = Request
        fields = ('repetition', 'until')


class SlotRequest(forms.ModelForm):
    class Meta(object):
        model = Slots
        fields = ('day', 'start_time', 'end_time')
        labels = {
            'day': 'Día',
            'start_time': 'Hora de Inicio',
            'end_time': 'Hora de Fin',
        }
    
    start = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    end = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])


SlotsFormset = modelformset_factory(
    Slots,
    fields=('day', 'start_time', 'end_time', ),
    extra=1,
    widgets={'day': DateTimeInput(format="%d/%m/%y")}
)


class RequestToReservationForm(forms.ModelForm):
    class Meta(object):
        model = Reservation
        fields = ('name', 'classroom')
        labels = {
            'name': 'Nombre de reserva',
            'classroom': 'Aulas',
        }

    classroom = forms.ModelChoiceField(queryset=Classroom.objects.all())


class LabUserSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.labUser = True
        if commit:
            user.save()
        return user


RequestSwFormset = modelformset_factory(
    Request_SW,
    fields=('sw',),
    extra=1,
)

templates/SW/asignarAula.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'sws' %}">SWs</a>
        </li>
        <li class="breadcrumb-item active">Asignar a Aula</li>
    </ol>
{% endblock hilos %}

{% block content %}
    <!-- alerta sw -->
    {% if not existen_sws %}
    <div class="card card-formAulas mx-auto alert alert-warning">
        <div class="card-body">
            <div class="form-group">
                Es necesario crear un <b>SW</b> previamente a su asignación.
            </div>
            <div class="form-group mb-0">
                <a href="{% url 'swCreate' %}" class="btn btn-success btn-block">Crear SW</a>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- alerta aula -->
    {% if not existen_aulas %}
    <div class="card card-formAulas mx-auto alert alert-warning">
        <div class="card-body">
            <div class="form-group">
                Es necesario crear una <b>Aula</b> previamente.
            </div>
            <div class="form-group mb-0">
                <a href="{% url 'aulaCreate' %}" class="btn btn-success btn-block">Crear Aula</a>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- alerta so -->
    {% if not existen_sos %}
    <div class="card card-formAulas mx-auto alert alert-warning">
        <div class="card-body">
            <div class="form-group">
                Es necesario crear un <b>SO</b> previamente a su asignación.
            </div>
            <div class="form-group mb-0">
                <a href="{% url 'soCreate' %}" class="btn btn-success btn-block">Crear SO</a>
            </div>
        </div>
    </div>
    {% endif %}

    <form method="POST" id="formAssigment">
        {% csrf_token %}
        <div class="card card-formAulas mx-auto">
            <div class="card-body">
                <div class="form-group">
                    <div class="form-label-group" style="text-align: center;">
                        <h5>Asignar SW a Aula</h5>
                        <hr>
                    </div>
                </div>
                <div>
                    <div id="div_id_sw" class="form-group">
                        <label for="id_sw" class="col-form-label  requiredField">
                            SW
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="">
                            <select name="sw" class="select form-control form-control-chosen" required="" id="id_sw">
                                <option value="" selected="">---------</option>
                                {% for sw in sws %}
                                <option value="{{sw.id}}">{{sw}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div id="div_id_so" class="form-group">
                        <label for="id_so" class="col-form-label  requiredField">
                            SO
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="">
                            <select name="so" class="select form-control" required="" id="id_so">
                                <option value="" selected="">---------</option>
                                {% for so in sos %}
                                <option value="{{so.id}}">{{so}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div id="div_id_aula" class="form-group">
                        <label for="id_aula" class="col-form-label  requiredField">
                            Aula
                            <span class="asteriskField">*</span>
                        </label>
                        <div class="">
                        <select name="aula" class="select form-control" required="" id="id_aula">
                            <option value="" selected="">---------</option>
                            {% for aula in aulas %}
                            <option value="{{aula.id}}">{{aula}}</option>
                            {% endfor %}
                        </select>
                        </div>
                    </div>
                    {%  if not existen_aulas or not existen_sos or not existen_sws %}
                    <div class="form-group">
                        <button disabled class="btn btn-dark btn-block" type="submit">Asignar</button>
                    </div>
                    {% else %}
                    <div class="form-group">
                        <button id="assigmentBtn" onclick="assigment()" type="submit" class="btn btn-primary btn-block" >
                            <span id="assigmentSpinner" class="spinner-border spinner-border-sm" role="status" hidden="true"></span>
                            <span id="assigmentText">Asignar</span>
                        </button>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </form>

    <script type="text/javascript" src="{% static 'js/fn.chosen.js' %}"></script>
    <script type="text/javascript">
        function assigment() {
            form = document.getElementById('formAssigment');

            if (!form.checkValidity()) {
                return false;
            }
            $('#assigmentBtn').attr('disabled', true);
            $('#assigmentSpinner').attr('hidden', false);
            $('#assigmentText').text('Asignando...');
            form.submit();
        }
    </script>
{% endblock content %}

templates/SW/asignarPC.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'sws' %}">SWs</a>
        </li>
        <li class="breadcrumb-item active">Asignar a PC</li>
    </ol>
{% endblock hilos %}

{% block content %}
    <!-- alerta sw -->
    {% if not existen_sws %}
    <div class="card card-formAulas mx-auto alert alert-warning">
        <div class="card-body">
            <div class="form-group">
                Es necesario crear un <b>SW</b> previamente a su asignación.
            </div>
            <div class="form-group mb-0">
                <a href="{% url 'swCreate' %}" class="btn btn-success btn-block">Crear SW</a>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- alerta pc -->
    {% if not existen_pcs %}
    <div class="card card-formAulas mx-auto alert alert-warning">
        <div class="card-body">
            <div class="form-group">
                Es necesario crear una <b>PC</b> previamente a su asignación.
            </div>
            <div class="form-group mb-0">
            <a href="{% url 'pcCreate' %}" class="btn btn-success btn-block">Crear PC</a>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- alerta so -->
    {% if not existen_sos %}
    <div class="card card-formAulas mx-auto alert alert-warning">
        <div class="card-body">
            <div class="form-group">
                Es necesario crear un <b>SO</b> previamente a su asignación.
            </div>
            <div class="form-group mb-0">
                <a href="{% url 'soCreate' %}" class="btn btn-success btn-block">Crear SO</a>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="card card-formAulas mx-auto">
        <div class="card-body">
            <div class="form-group">
                <div class="form-label-group" style="text-align: center;">
                    <h5>Asignar SW a PC</h5>
                    <hr>
                </div>
            </div>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    {%  if not existen_pcs or not existen_sos or not existen_sws %}
                    <div class="form-group">
                            <button disabled type="submit" class="btn btn-dark btn-block">Asignar</button>
                        </div>
                    {% else %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Asignar</button>
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>


    <script type="text/javascript">
        let select_pc = document.getElementById("id_pc");

        select_pc.onchange = function () {
            let id_pc = parseInt(select_pc.value);

            if (id_pc) {
                let csrftoken = Cookies.get('csrftoken');

                fetch(`/ajax/so/?pc_id=${id_pc}`, {
                    method: "get",
                    credentials: "same-origin",
                    headers: {
                        "X-CSRFToken": csrftoken,
                        "Accept": "application/json",
                        "Content-Type": "application/json"
                    }
                }).then(function (res) {
                    return res.text();
                }).then(function (html) {
                    console.log(`html = ${html}`);
                    $('#id_so').html(html);
                }).catch(function (ex) {
                    console.log("error", ex);
                });
            }
            else {
                $('#id_so').html('');
            }
        }
    </script>
    <script type="text/javascript" src="{% static 'js/fn.chosen.js' %}"></script>
{% endblock content %}

templates/SW/crear.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'sws' %}">SWs</a>
        </li>
        {% if sw.id %}
            <li class="breadcrumb-item active">Editar SW</li>
        {% else %}
            <li class="breadcrumb-item active">Crear SW</li>
        {% endif %}
    </ol>
{% endblock hilos %}

{% block content %}
    <div class="card card-formAulas mx-auto">
        <div class="card-body">
            <div class="form-group">
                <div class="form-label-group text-center">
                    {% if sw.id %}
                        <h5>Editar SW</h5>
                    {% else %}
                        <h5>Crear SW</h5>
                    {% endif %}
                    <hr>
                </div>
            </div>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/SW/lista.html
{% extends 'base.html' %}
{% load static %}
{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li class="breadcrumb-item active">SWs</li>
    </ol>
{% endblock hilos %}

<!-- Contenido de la Página-->
{% block content %}
    <div class="card mb-3">
        <div class="card-header">
            <div class="row">
                <div class="col-8 col-xs-8 d-flex align-items-center">
                    <i class="fas fa-table mr-1"></i>
                     Listado de Software
                </div>
                <div class="col-4 col-xs-4 text-right">
                    <a class="btn btn-success btn-md" href="{% url 'swCreate' %}">
                        Crear
                    </a>
                </div>
            </div>
        </div>
        <div class="card-body" id="elementCard">  
            <div class="table-responsive">
                <table class="table w-100 table-hover display" id="" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody id="myTable">
                        {% for sw in sws %}
                        <tr>
                            <td>{{ sw.name }}</td>
                            <td>{{ sw.description }}</td>
                            <td>
                                <a href="{% url 'swDetail' sw.id %}" class="text-warning text-decoration-none">
                                    <i class="material-icons" title="Ver" data-toggle="tooltip">remove_red_eye</i>
                                </a>
                                <a href="{% url 'swEdit' sw.id %}" class="text-warning text-decoration-none">
                                    <i class="material-icons" title="Editar" data-toggle="tooltip">edit</i>
                                </a>
                                <a href="{% url 'swDelete' sw.id %}" class="text-danger text-decoration-none">
                                    <i class="material-icons" title="Eliminar" data-toggle="tooltip">delete</i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'js/fn.datatables.js' %}"></script>
{% endblock content %}

templates/SW/ver.html
{% extends 'base.html' %}

{% block hilos %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'sws' %}">SW</a>
        </li>
        <li class="breadcrumb-item active">SW {{ sw.name }}</li>
    </ol>
{% endblock hilos %}

{% block content %}
    <div class="card card-formAulas mx-auto">
        <div class="card-body">
            <div class="form-group">
                <div class="form-label-group" style="text-align: center;">
                    <h5>Ver detalle SW {{ sw.name }}</h5>
                    <hr>
                </div>
            </div>
            <div class="form-group">
                <div class="form-label-group">
                    <b>Nombre:</b> {{ sw.name }}
                </div>
            </div>
            <div class="form-group">
                <div class="form-label-group">
                    <b>Descripcion:</b> {{ sw.description }}
                </div>
            </div>
            <div class="form-group">
                <a href="{% url 'swEdit' sw.id %}" class="btn btn-primary btn-block">Editar</a>
                <a href="{% url 'swDelete' sw.id %}" class="btn btn-danger btn-block">Eliminar</a>
            </div>
            <input type="hidden" id="swId" value="{{ sw.id }}" />
        </div>
    </div>
{% endblock content %}